sjasmplus sin_leches_menu_if2.asm
copy /b menuif2.rom+          ^
        seachange.rom+        ^
        48.rom+               ^
        Backgammon.rom+       ^
        lechesaa.rom+         ^
        Cookie.rom+           ^
        sinleches.rom+        ^
        Pssst.rom+            ^
        testrom.rom+          ^
        Gyruss.rom+           ^
        testrom48.rom+        ^
        JetPac.rom+           ^
        se2.rom+              ^
        Chess.rom+            ^
        inves.rom+            ^
        Planetoids.rom+       ^
        HoraceSpiders.rom+    ^
        QBert.rom+            ^
        SpaceRaiders.rom+     ^
        ReturnJedi.rom+       ^
        TranzAm.rom+          ^
        StarWars.rom+         ^
        ShadowUnicorn.rom+    ^
        Deathchase.rom+       ^
        HungryHorace.rom+     ^
        JetSetWilly.rom+      ^
        LocoMotion.rom+       ^
        LalaPrologue.rom+     ^
        PanamaJoe.rom+        ^
        ManicMiner.rom+       ^
        Popeye.rom+           ^
        MiscoJones.rom        ^
    romsif2.rom
