\emuscriptoria\sjasmplus kartusho.asm
cd ..\..\..\firmware\roms
copy /b ..\..\software\otros\if2\kartusho.rom+   ^
        48.rom+               ^
        lechesaa.rom+         ^
        sinleches.rom+        ^
        SinclairTestDup.rom+  ^
        testrom48.rom+        ^
        se2.rom+              ^
        inves.rom+            ^
        seachange.rom+        ^
        Backgammon.rom+       ^
        Cookie.rom+           ^
        Pssst.rom+            ^
        Gyruss.rom+           ^
        JetPac.rom+           ^
        Chess.rom+            ^
        Planetoids.rom+       ^
        HoraceSpiders.rom+    ^
        SpaceRaiders.rom+     ^
        TranzAm.rom+          ^
        ShadowUnicorn.rom+    ^
        HungryHorace.rom+     ^
        LocoMotion.rom+       ^
        PanamaJoe.rom+        ^
        Popeye.rom+           ^
        MiscoJones.rom+       ^
        ReturnJedi.rom+       ^
        StarWars.rom+         ^
        Deathchase.rom+       ^
        JetSetWilly.rom+      ^
        LalaPrologue.rom+     ^
        gw03.rom+             ^
        QBert.rom             ^
    ..\..\software\otros\if2\kartusho.rom
cd ..\..\software\otros\if2
